### ISSUE TITLE
[Enhancement] Add OG/SW Teleport Cloaks( Guild Cloaks)

### ISSUE THREAD

**Issue by mohcow** [Justw8/TeleportMenu#33] opened 2024-09-05 16:26 UTC
Would be cool if you could add the Guild OG/SW TP Cloaks aswell:

https://www.wowhead.com/item=63207/wrap-of-unity
https://www.wowhead.com/item=63206/wrap-of-unity
https://www.wowhead.com/item=63353/shroud-of-cooperation
https://www.wowhead.com/item=63352/shroud-of-cooperation
https://www.wowhead.com/item=65360/cloak-of-coordination
https://www.wowhead.com/item=65274/cloak-of-coordination

obviously you have to press the button twice, once to equip and secondly to use. Maybe even add a way to switch back after teleporting?

**Comment by Justw8** [comment] 2024-09-06 13:48
Duplicate of https://github.com/Justw8/TeleportMenu/issues/12

You can post them here :)

Trying to keep it all in 1 place.

**Closed by Justw8** 2024-09-06 13:48 UTC
